<script setup>

</script>

<template>
  <div>
    <pre id="pre">

                                                                  ...............   .  ... ....                     
                                                                .. .....'...''...................
                                                            ..''',,,;:c:;,,,,'..'',,,;;,,'.......... ..
                                                          .';;:cclllooodocc::;;:::cclllcc::,,,'.''......................
                                                        ,coooodddddddxdddoooooodddddoooooolllcccc::;;;::;;;;,,,,,'''........
                                                        :odddddddddxxxxxxxxxxxxkxxxxxxxxxxdddooooololllllcc:::::::;;;,,,''.......
                                                      .ldddddxxxxxxxxxxkxxxkkkkkkkxxkkxxxxxxxxddddooooooooolllcccccc::::;;;,,'.......
                                                    ,dddddddxxxxxxxxkkkkkkkkkkkkkkkkkkxxkxxxxxxdxddddoodddooolllllcclcccc::;;,,,'....
                                                    :xdddddxxxxxxkxxkkkkkkkkkkkkOkkkkkkkkkkxxxxxxxxddddddddooooolllllllccc:::::;;,,'...
                                                  :xxdddddxxxxkkkkkkkkkkkkkkOOOkkkkkkkkkkkxxxxxxxddddddoddooooolllccccccccc:::;;,,'.....
                                                  ,xxxddddxxxxxkkkkkkkkkkkkkOOkkkOkkkkkkkkkkkxxxxxddddooooooooolllccllcccccc::::;;;,'....
                                                .odddddxxxxxkkkkkkkkkkkkkkkkOkkkOkkkkkkkkkxxxxxxddddddooollolllcccccccccccc:::::;;,'......
                                                cddddxxxxxxxkkkkkkkkkkkkkkkkkkkkOOkkkkkkkkxxdddddddooooolllllcccccccccccc:::::;;;;,''.....
                                                'ldddxxdxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxdddddoolollllllccc:cccccc::::::;;;;;,'''.....
                                                :lodddxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxddodoooollllllccc::::c::c::::::;;;;;;,,''......
                                              'clooddxxxdxxxxkkkkxxxxxkkkkkkkkkkkkkxxxxxddddddoooooolllllccccc:::cc::::;;;;;;;;;;,,,,'....
                                              .cllloodddddddxxxxxxxxxxxxxxkkkkkkkkkxxxxddddooollllllllccccccccc:::::::;;;;;;;;;;;,,,,,''....
                                              ;llllooddddddddxxxxddxxxxxxxxxxxxxxxxxdddddoooollllllllcccccccccc:::::;;;;;;;;;;;;;,,,,''.....
                                            .cllllooodddddddxdddddxxxxxxxxxxxxddxdddoooolllllllllllllllccccc:::::;;;;;;;;;;;;;;,,,,''.......
                                            ,loooooodddddddddxxxddxxddxxxxxxxddddddddooolllllllllllllllcccccc:::;;;;;;;;;;,,,,,,,'''........
                                            .clooddddddddddodxxxxxxdxxxxxxddddddddddooooolooollollllllllccccc::;;;;;;;;;;;,,,;,,,''........
                                            .loodddddddxxxdddxxxxxxxdxxxxxxxxxxxxddddddooooooloooolllllllcccc::;;;;;;;;,,,,,,,''''........
                                            :ldddxxxddxxxxdddxxxxxxdxxxxxxxxxxxxxxxxddddddoooooooollllllclccc:::;;;;,;,,,,,,,''..........
                                          .lodddddddddxddddddxxddddxxxxxxxxxxxxxxxxxdddddoooooooollllllcccc:::;;;,,,,,,,,,,''.........
                                          .:coodddddddddddooddddddoodddxxxxxxxxxxxxddddddddddddooooolllccccc:::;;;;,,',,,,,''.........
                                        .,;;::::::::ccccllllooooooodddddddddddddddddddddddddddoodooooolllcc:::;,,,,,',,,''''.........
                                        .',,'''''''',,,;:cccllollloodddooooododdddddddddddxxddddddddoollccc:::;;,,,,',,,,'''........  .
                                          ',,'''......'..,;:cclllcllollcc:::::ccllllloodddddddddooodooollccc:;;;;,,,,,,,,,,''.......... .
                                          .;::cc:::;;,,'.'';:cccccccc::;,''''....'',,;::clllcclllllololllc:::;;;,,,,,,,,,,,,'......... . .
                                          ,::;,,,'',,;;,,,,:cclccc:;;,,'..............',,;::::::::cccccccc:;,;,,,,,,',,,,,,''''.........
                                          .'..........'',,,;colllcc;,'...................'',;;;;;;;;;;;:::;;,,,,'',,,,,,,,''',''......
                                            ..    ';,',,,,,,;ooollc:,................',;;,,,,,,,,,,''''',,,,,,,'''',,,,,,,,,,,,,''....
                                              .. ..coolccc;,;:ddddoc:,....    ...       ..',,,,,,'''''.....'',,,,,'',,,,;;,,,,;;,,'...
                                              ,;,';lloodoocc:oxxxxdl:,'....  .....       ........'''''.......'',',',,,;;;;;;;;;;;,''..                 ...'..
                                              :;:::ccclccccloxxxxdol:;,'.....','.........'::,..   ..........'.'',,,,;;;;;;;::;;;;,'....          .....',;::;,.
                                            .c:;::cc:;;;:codxxxxolc:;;,,,''''',,,'',...':c::,.....    .......''',,;;;;:::::::;;;,'...           .'',,;,,'..'.
                                            'lc::;;;;:clloxdxkxdlc:::;:::;,,'''','',,;;;:::;;;;,,'...........'',,,,;::::::c:::;;,'...          ..'''..........
                                            :lllllllllooodxxxxolc:c:::c:c:::;;;,,,,'',,;;;,,,,,'''''''''..''',,;;;;::ccccc:::;;;,'...        ...''.............
                                            .looooooooddxxxxxxdlc:::;;:ccccccccccc:;;;,,,,,,,,,,,,'',,,,;;;;;;:::ccccccccc::::;;,,...        ........,,'''....'..
                                            'ooddddxxxxkkxkkxddoc:;;;;:::ccccccllollcc::::;;;;;;;;;;::::::::c:clllllcccc:::::;;,,'..        .....    .,;,,,....'.
                                            ;oddxxxkxkkkxkkxdoolc:;;;;:::ccccllooddddoollcclccllllclcccclllllccllllcccc:::::;;;,'...       .....   ...,;;,,,..;,.
                                            :oddxxxkkkxkxkxxdoolc:;;;;:::ccclloooddddxdxddddddooooooolllooolllllllcccccc::;;;;,'...       ..'''.......;;;;;,'':,
                                            codxxkkkkxxkxkxddol::;,,,,,;:::cclooddddxxxxxxxkxxxxdddddooooodollllcccc::::::;;;,,''..       ..,,,....'.';:::;,,::.
                                            codxxkkkkxxxxkxdol::,,',,,,;;;;;:cloddxxkkkkkkkkkkkkxxxxddddooooolllccc:::::::;;;,,''..       .',,'.',,;,':ll:;,:c,
                                            codxxkkkxxxxdddoc:;,,,;;:::c::;;;;clodxxkkkkkkkkkkkkkxxxddddooolllllcc::::::;;;;,,''''..     ..,,'..';c:,':ll:,;c;.
                                          .codxkkkkdxdddolc:;,,,;:::cc::::;,,:lodxxkkkkkkkkkkxxxxxdddooollllcccc:::::;;;;;;,,,''...     ..'...',;:;,;cc:,;:;.
                                          ;cldxxxxxdooolc:;'...'',,,;;;;;;;'';:lodxkkkkkkkkkkkxxddddoooollllccccc::;;;;;;;,,''''..      .....'',;cccc;,;:c,
                                          .;:lddddxdolc::;'......     ..'''...,:codxxkkkkkkkxkxddddoooooollllllcc::;;;;;;,,,,,''...      ..',;:cccccc::cc;.
                                          ,;:loooodollc;'....   .       .....,::clddxxkxxxkxxxxdddoooooolllllcccc::;;;;;;,,,,,'....      ...,;;;:::cccc;.
                                          .,:looloollooc;''''.............',;ccclllddxxxxxxxxxdddooollllllllccccc:::;;;;,,,,,'....       ..',,;;::::;'.
                                          .';clllllcclc:,;,,,'.'''.''..'',;:ccllllloodxxdxxxxdddooollllllllcccc::::;;;,,,,'''.....       ..',;;,,..
                                          .,;cllllcc:c:,',,,...,,,'.'','',;;:clllllooodddddddddoooollllccccccc:::;;;,,,'''''.....        ......
                                          .';clllc::::,'''..'',;;;,''',,,,,;;:ccclllllooddddddooollllccccccc:::::;,,,,,'''''......
                                          '';cccc:;,,,......,;::c:;,'''',,',,,;::cccllooooooooooolllcccccccc::::;;,,,,,''.......
                                          '',cc::;,'........';:::,'''.....''',,;;;:::cclooooooooollccccccc:::::;;,,,''''...... .
                                          ,,,:c:;:;,...........'..............''',;:::ccloooooollllllccccc::::;;;,,,''''......
                                          .:,;:::c:,''.';,;;,,,,,'................',;:::cllolooollllcccccc::::;;,,,''.'....... .
                                          ';''::::::,,;:c:::cclllllcclc:;'........'';;;;:cloooolllllccccc::::;,,,,,'''.....
                                          .,.';:;:c:,;;:cccc:cclllccccc::;;;;;;;;;;;;;;;;:cllolllllccc::::;;;;,,,''''......
                                          .;.',;;:c:,;:ccccc::;:;::ccc:cccc:cccccc::;:,,;:cllllccccc:::;;;;;;,,,''.........               .
                                          c,''.,:::::;;:ccc::;;;;;;;:cccccccccccclcc::,',;::cccccc::;;;;;,,,,,,''........
                                        ',....';;;;,,;;:cc:::;,,;;;:ccccccccccccccc:;,,',;:::::::;;;,;;,,,,,'''.........
                                        .......',;;;;;;::ccc::;;;;;;:cccccccccccccc::;;,'',;;:::;;;;;,,,,''''''.........
                                    ...... ....',,;;,,,;:ccc:::::::cclllllcccccc:c:::;;;'''',;;,,,,,,,,''''..........
                                ...............','''',,:::::cccc::cclloolllcccc:::;;,,,,,,'''',,''''''......... ..
                              ........ .    ...'.....';:;;:cccccccccllllllclcc:::;;,,',,,''.'''....'..........
                            ...... ....      ...''...',,;;;:::cc:cccccclcccccc::;:;;;,'''''.................                           ..
                          ........ ...          .''.',,,',;,;:::::::::;::c::;;;;;,,,,,'.................                            ..                                       ..
                        .......                 ...'',,..,,',,,;,,,,;;,,;;;,,''',''.'''.......  ......                             ..
                      ...                        ...''.'''....''''''',,;,,'.'..'........                                       ...... .
                                                  ............ ......'''....'.......                                          ........
                                                  ..........    ......'..........  .                                         .. .....    ..
                                                    .......     . .......... .. . .                                         .........  ...
                                                      ......   .   .........  .                                             ......... ......
                                                      .....        ...  ...   .                           . .              ................
                ......                                .....       .    .                                              .. ..................
              ...........                                  .                                                               .................
            .........      .                                                                                     ....    ...................
        .............                                                                                          .....................  .....
  .......... ..  .                                                                                            ............................
            ... .                                                                                          ........   ....................
                ...                                                                              ..  ........................................
                  .                                                                             ...........................................
                                                                                              ...........................................
                                                                                                  ......................................
                                                                                                    .................................
                                                                                                    ...............................
                                                                                                ..............................
                                                                                              ............................
                                                                                                .....................


    </pre>
  </div>
</template>


<style lang="scss" scoped>
pre {
  position: absolute;
  font-size: .4vw;
  font-family: 'Courier New', Courier, monospace;
  white-space: pre;
  color: #ffffff;

}

@media only screen and (max-width: 700px) {

  pre {
    font-size: 1.3vw;
    position: relative;
  }
}
</style>