<script setup>

</script>

<template>
  <div>
    <pre id="pre">
              ................
            .,;:cll:;;;::c:;,'............
          .lodddxxxddxxxxdddooolcccc::;;,,'....
        ;dddxxxxxkkkkkkkkxxxxdddoooollccc::;,'..
        cxddxxkkkkkkkOkkkkkkxxxxddddooollccc::;,'..
      ;xdxxxkkkkkkkkkkkkkkkxxxdddoolllccccc:::;,...
      .odxxxxkkkkkkkkkkkkkkxxdddooollcccccc::;;;,'..
      ;oddddxxxxxxxkkkkkxxxddooollllcc::::;;;;;;,'..
    'lloddddxddxxxxxxxxdddoolllllcccc::;;;;;;;,,'...
    :oodddddxxxxxxxdddddoollllllllcc::;;;;;,,,''....
    .oddddxddxxxxxxxxxxdddooooollllcc:;;;;,,,'''....
    :odddddddxxddxxxxxxxddddoooollccc:;;,,,,''....
  .;;;;;::lloolodddddddddddddddoolc::;,,,,''....
  .,;,,''.,:clclc:;;;;:cloooooooolc:;;,,,,,'.....
    '''.',,,;llc:,'.......',;;::::::;,,',,,,'''....
    . .:::;,loo:'.........',,,,'''',,,',,,,,,,'..
    .;;lllcldxdc,.......  ''........'',,;;;;;;,..      ..','
    ;::::cldxdl:;;,,',,'',::,'.......',;:::::;,.      .'.....
    looooddxxl:::cc::::;,,,,,,'',,,,;:::ccc:;;'.    .....'....
    .odxxkkkxol:;::cclooollcccccccccccllcc:::;,.    ... ..;,'..
    'oxkkxxxdl:;;;::clodxxxxxxdddoooollcc:::;,'.   .',...,:;,;.
    ,dxkxxxdl:,,;:::;:oxxkkkkkxxxddollc::::;,,'.   .'.';;;l;;'
    :oxxdol:,..'',;;',cdxkkkkkxddoollcc::;;;,,'.   ..';:::;;.
  .:ooool;..........;codxxxxxdooolllcc:;;;,,'..   .';::c:'
  .;lllcl;;,.'''.',:lllodxxxdoollllcc::;;,,'...   .','..
  .,llc:;'''';,''',;:clloddddollcccc::;,,''...
  .,c:;'....;:,'...',;:ccloooollccc::;,,'....
  .,;::,',,,;;,,'.....';::loolllccc:;,,''...
  .',;c;;cccccccc:;;;;;;;;clllcc::;;,,''...
  '..;:;;:c:;;;:ccccccc:;,;cc:::;;,,,'....
  ....,;,,:c::;;:ccccccc:;,';;;;,,,''.....
  ........'.';::cc:clollc::;,,,''''''.....
  ......    .'.,,;;:::c:cc::;;,,..........
  ...          .''.,.''',,,,'''......                   .
        ...... ...'......                     ....
        ....   ......                       .... ..
          ..    . .                         ........
  .....                                             ..  .........
  ......                                              ..............
  .                                         ...................
                              ....................
                                .................
                              ...............
                                ........


                                      ...
                                        .,,
                                        ..
  </pre>
  </div>
</template>


<style lang="scss" scoped>
pre {
  font-size: .5vw;
  font-family: 'Courier New', Courier, monospace;
  white-space: pre;
  color: #ffffff;

}

@media only screen and (max-width: 700px) {

  pre {
    font-size: 2vw;
  }
}
</style>